//channel action types


export const CHANNEL_PRESENCE_CHANGE = "CHANNEL_PRESENCE_CHANGE";
export const SET_ACTIVE_CHANNEL = "SET_ACTIVE_CHANNEL";
export const LOAD_CHANNELS = "LOAD_CHANNELS"
export const NEW_CHANNEL_MESSAGE = "NEW_CHANNEL_MESSAGE";
export const CHANNEL_DELETE_MESSAGE = "CHANNEL_DELETE_MESSAGE";
export const CHANNEL_UPDATE_MESSAGE = "CHANNEL_UPDATE_MESSAGE"; // ? NO UPDATE FOR NOW




// presence
export const PRESENCE_CHANGE = "PRESENCE_CHANGE" // 


// TODO: ADD MORE TYPES



// global actions

export const SET_USER = "SET_USER";
export const RESET_USER = "RESET_USER";
export const SET_USER_CHANNEL = "SET_USER_CHANNEL";


